name: Operator ChatGPT Integration

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-operator-engine:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install httpx

      - name: Run Operator Engine
        run: python scripts/run_pipeline.py > result.log

      - name: Enviar para ChatGPT (opcional)
        run: |
          python scripts/send_to_openai.py result.log